# Custom Inputs for get_indicators() ======================

# PARAMETERS ----------------------------------------------

params_default = {
    'candle_colors': {'indicator_color': 'QQEMOD'},
    'aVWAP': { 
              'peaks_valleys': False,
              'peaks_valleys_avg': False,
              'peaks_valleys_params': { 'periods': 20, 'max_aVWAPs': None },
              'OB': True,
              'OB_avg': False,
              'OB_params': { 'periods': 20, 'max_aVWAPs': 5 },
              'gaps': False,
              'gaps_avg': False,
              'gaps_params': { 'max_aVWAPs': 10 },
              'avg_lookback': 5,
              'keep_OB_column': True,
             },
    'OB': { 'periods': 20 },
    'StDev': {
              'centreline': 'peaks_valleys_avg', 
              'peaks_valleys_params': { 'periods': 20, 'max_aVWAPs': None }, 
              # 'gaps_params': { 'max_aVWAPs': 10 }, 
              'std_lookback': 50,
              'avg_lookback': 20,
              },
    'SMA': {'periods': [20]},
    'liquidity': {'swing_length': 20, 'range_percent': 0.1},
    'TTM_squeeze': {'bb_length': 20, 
                    'bb_std_dev': 2.0, 
                    'kc_length': 20, 
                    'kc_mult': 1.5, 
                    'use_true_range': True},
    # 'divergence_ATR':    {'period':  80, 'lookback': 30},
    'divergence_OBV':    {'period': 80, 'lookback': 40},
    'divergence_Volume': {'period': 80, 'lookback': 40},
    'divergence_Fisher': {'period': 80, 'lookback': 40},
    'divergence_Vortex': {'period': 80, 'lookback': 40},
}

params_weekly = {
    'candle_colors': {'indicator_color': 'StDev', 
                      'custom_params': {'StDev': {'std_lookback': 4, 
                                                  'avg_lookback': 4,
                                                  'centreline': 'peaks_valleys_avg',
                                                  'peaks_valleys_params': {
                                                      'periods': 4,
                                                      'max_aVWAPs': None
                                                  }}}},
    'aVWAP': { 
              'peaks_valleys': False,
              'peaks_valleys_avg': True,
              'peaks_valleys_params': { 'periods': 4, 'max_aVWAPs': None },
              'OB': True,
              'OB_avg': False,
              'OB_params': { 'periods': 4, 'max_aVWAPs': None },
              'gaps': False,
              'gaps_avg': False,
              'gaps_params': { 'max_aVWAPs': 4 },
              'avg_lookback': 4,
              'keep_OB_column': True,
             },
    'OB': { 'periods': 4 },
    'StDev': {
              'centreline': 'peaks_valleys_avg', 
              'peaks_valleys_params': { 'periods': 4, 'max_aVWAPs': None }, 
              # 'gaps_params': { 'max_aVWAPs': 10 }, 
              'std_lookback': 4,
              'avg_lookback': 4,
              },
    'SMA': {'periods': [20]},
    'liquidity': {'swing_length': 4, 'range_percent': 0.1},
    'TTM_squeeze': {'bb_length': 20, 
                    'bb_std_dev': 2.0, 
                    'kc_length': 20, 
                    'kc_mult': 1.5, 
                    'use_true_range': True},
    # 'divergence_ATR':    {'period':  80, 'lookback': 30},
    'divergence_OBV':    {'period': 26, 'lookback': 26},
    'divergence_Volume': {'period': 26, 'lookback': 26},
    'divergence_Fisher': {'period': 26, 'lookback': 26},
    'divergence_Vortex': {'period': 26, 'lookback': 26},
}

params_daily = {
    'candle_colors': {'indicator_color': 'StDev', 
                      'custom_params': {'StDev': {'std_lookback': 20, 
                                                  'avg_lookback': 20,
                                                  'centreline': 'peaks_valleys_avg',
                                                  'peaks_valleys_params': {
                                                      'periods': 20,
                                                      'max_aVWAPs': None
                                                  }}}},
    'aVWAP': { 
              'peaks_valleys': False,
              'peaks_valleys_avg': False,
              'peaks_valleys_params': { 'periods': 20, 'max_aVWAPs': None },
              'OB': True,
              'OB_avg': False,
              'OB_params': { 'periods': 20, 'max_aVWAPs': None },
              'gaps': False,
              'gaps_avg': False,
              'gaps_params': { 'max_aVWAPs': 20 },
              'avg_lookback': 5,
              'keep_OB_column': False,
             },
    'OB': { 'periods': 20 },
    'StDev': {
              'centreline': 'peaks_valleys_avg', 
              'peaks_valleys_params': { 'periods': 20, 'max_aVWAPs': None }, 
              # 'gaps_params': { 'max_aVWAPs': 10 }, 
              'std_lookback': 40,
              'avg_lookback': 20,
              },
    'SMA': {'periods': [20]},
    'liquidity': {'swing_length': 20, 'range_percent': 0.1},
    'TTM_squeeze': {'bb_length': 20, 
                    'bb_std_dev': 2.0, 
                    'kc_length': 20, 
                    'kc_mult': 1.5, 
                    'use_true_range': True},
    # 'divergence_ATR':    {'period':  80, 'lookback': 30},
    'divergence_OBV':    {'period': 50, 'lookback': 50},
    'divergence_Volume': {'period': 50, 'lookback': 50},
    'divergence_Fisher': {'period': 50, 'lookback': 50},
    'divergence_Vortex': {'period': 50, 'lookback': 50},
}

params_1hour = {
    'candle_colors': {'indicator_color': 'StDev', 
                      'custom_params': {'StDev': {'std_lookback': 16, 
                                                  'avg_lookback': 16,
                                                  'centreline': 'peaks_valleys_avg',
                                                  'peaks_valleys_params': {
                                                      'periods': 16,
                                                      'max_aVWAPs': None
                                                  }}}},
    'aVWAP': { 
              'peaks_valleys': False,
              'peaks_valleys_avg': False,
              'peaks_valleys_params': { 'periods': 16, 'max_aVWAPs': None },
              'OB': True,
              'OB_avg': False,
              'OB_params': { 'periods': 16, 'max_aVWAPs': 5 },
              'gaps': False,
              'gaps_avg': False,
              'gaps_params': { 'max_aVWAPs': 16 },
              'avg_lookback': 16,
              'keep_OB_column': True,
             },
    'OB': { 'periods': 16 },
    'StDev': {
              'centreline': 'peaks_valleys_avg', 
              'peaks_valleys_params': { 'periods': 16, 'max_aVWAPs': None }, 
              # 'gaps_params': { 'max_aVWAPs': 10 }, 
              'std_lookback': 16,
              'avg_lookback': 16,
              },
    'SMA': {'periods': [21]},
    'liquidity': {'swing_length': 64, 'range_percent': 0.1},
    'TTM_squeeze': {'bb_length': 16, 
                    'bb_std_dev': 2.0, 
                    'kc_length': 16, 
                    'kc_mult': 1.5, 
                    'use_true_range': True},
    # 'divergence_ATR':    {'period':  80, 'lookback': 30},
    'divergence_OBV':    {'period': 128, 'lookback': 64},
    'divergence_Volume': {'period': 128, 'lookback': 64},
    'divergence_Fisher': {'period': 128, 'lookback': 64},
    'divergence_Vortex': {'period': 128, 'lookback': 64},
}

params_5min = {
    'candle_colors': {'indicator_color': 'StDev', 
                      'custom_params': {'StDev': {'std_lookback': 20, 
                                                  'avg_lookback': 20,
                                                  'centreline': 'peaks_valleys_avg',
                                                  'peaks_valleys_params': {
                                                      'periods': 20,
                                                      'max_aVWAPs': None
                                                  }}}},
    'aVWAP': { 
              'peaks_valleys': False,
              'peaks_valleys_avg': False,
              'peaks_valleys_params': { 'periods': 20, 'max_aVWAPs': None },
              'OB': True,
              'OB_avg': False,
              'OB_params': { 'periods': 20, 'max_aVWAPs': 1 },
              'gaps': False,
              'gaps_avg': False,
              'gaps_params': { 'max_aVWAPs': 10 },
              'avg_lookback': 10,
              'keep_OB_column': False,
             },
    'OB': { 'periods': 20 },
    'StDev': {
              'centreline': 'peaks_valleys_avg', 
              'peaks_valleys_params': { 'periods': 20, 'max_aVWAPs': None }, 
              # 'gaps_params': { 'max_aVWAPs': 10 }, 
              'std_lookback': 20,
              'avg_lookback': 20,
              },
    'SMA': {'periods': [20]},
    'liquidity': {'swing_length': 40, 'range_percent': 0.1},
    'TTM_squeeze': {'bb_length': 20, 
                    'bb_std_dev': 2.0, 
                    'kc_length': 20, 
                    'kc_mult': 1.5, 
                    'use_true_range': True},
    # 'divergence_ATR':    {'period':  80, 'lookback': 30},
    'divergence_OBV':    {'period': 128, 'lookback': 80},
    'divergence_Volume': {'period': 128, 'lookback': 80},
    'divergence_Fisher': {'period': 128, 'lookback': 80},
    'divergence_Vortex': {'period': 128, 'lookback': 80},
}

# INDICATORS ----------------------------------------------

ind_default = [
    'aVWAP', 
    'candle_colors', 
    'liquidity', 
    # 'BoS_CHoCH', 
    # 'ZScore', 
    # 'StDev', 
    # 'QQEMOD',
    # 'banker_RSI', 
    # 'SMA',
    # 'supertrend',
    'OB',
    # 'TTM_squeeze',
    # 'divergence_ATR', 
    'divergence_Vortex',
    'divergence_Fisher',
    'divergence_OBV',
    'divergence_Volume'
]

ind_weekly = [
    'aVWAP', 
    'candle_colors', 
    # 'liquidity', 
    # 'BoS_CHoCH', 
    # 'ZScore', 
    # 'StDev', 
    # 'QQEMOD',
    # 'banker_RSI', 
    # 'SMA',
    # 'supertrend',
    'OB',
    # 'TTM_squeeze',
    # 'divergence_ATR', 
    'divergence_Vortex',
    'divergence_Fisher',
    'divergence_OBV',
    'divergence_Volume'
]

ind_daily = [
    'aVWAP', 
    'candle_colors', 
    # 'liquidity', 
    # 'BoS_CHoCH', 
    # 'ZScore', 
    # 'StDev', 
    # 'QQEMOD',
    # 'banker_RSI', 
    # 'SMA',
    # 'supertrend',
    'OB',
    # 'TTM_squeeze',
    # 'divergence_ATR', 
    'divergence_Vortex',
    'divergence_Fisher',
    'divergence_OBV',
    'divergence_Volume'
]

ind_1hour = [
    'aVWAP', 
    'candle_colors', 
    # 'liquidity', 
    # 'BoS_CHoCH', 
    # 'ZScore', 
    # 'StDev', 
    # 'QQEMOD',
    # 'banker_RSI', 
    # 'SMA',
    # 'supertrend',
    'OB',
    # 'TTM_squeeze',
    # 'divergence_ATR', 
    'divergence_Vortex',
    'divergence_Fisher',
    'divergence_OBV',
    'divergence_Volume'
]

ind_5min = [
    'aVWAP', 
    'candle_colors', 
    'liquidity', 
    # 'BoS_CHoCH', 
    # 'ZScore', 
    # 'StDev', 
    # 'QQEMOD',
    # 'banker_RSI', 
    # 'SMA',
    # 'supertrend',
    'OB',
    'TTM_squeeze',
    # 'divergence_ATR', 
    'divergence_Vortex',
    'divergence_Fisher',
    'divergence_OBV',
    'divergence_Volume'
]
