params_default = {
    'candle_colors': {'indicator_color': 'QQEMOD'},
    'aVWAP': { 
              'peaks_valleys': False,
              'peaks_valleys_avg': True,
              'peaks_valleys_params': { 'periods': 21, 'max_aVWAPs': None },
              'OB': True,
              'OB_avg': False,
              'OB_params': { 'periods': 21, 'max_aVWAPs': 5 },
              'gaps': False,
              'gaps_avg': False,
              'gaps_params': { 'max_aVWAPs': 10 },
              'avg_lookback': 5,
              'keep_OB_column': True,
             },
    'StDev': {
              'centreline': 'peaks_valleys_avg', 
              'peaks_valleys_params': { 'periods': 20, 'max_aVWAPs': None }, 
              # 'gaps_params': { 'max_aVWAPs': 10 }, 
              'std_lookback': 75,
              'avg_lookback': 21,
              },
    'SMA': {'periods': [21]},
    'TTM_squeeze': {'bb_length': 20, 
                    'bb_std_dev': 2.0, 
                    'kc_length': 20, 
                    'kc_mult': 1.5, 
                    'use_true_range': True},
    # 'divergence_ATR':    {'period':  80, 'lookback': 30},
    'divergence_OBV':    {'period': 100, 'lookback': 40},
    'divergence_Volume': {'period': 100, 'lookback': 40},
    'divergence_Fisher': {'period': 100, 'lookback': 40},
    'divergence_Vortex': {'period': 100, 'lookback': 40},
}

params_weekly = {
    'candle_colors': {'indicator_color': 'StDev', 
                      'custom_params': {'StDev': {'std_lookback': 4, 
                                                  'avg_lookback': 4,
                                                  'centreline': 'peaks_valleys_avg',
                                                  'peaks_valleys_params': {
                                                      'periods': 4,
                                                      'max_aVWAPs': None
                                                  }}}},
    'aVWAP': { 
              'peaks_valleys': False,
              'peaks_valleys_avg': True,
              'peaks_valleys_params': { 'periods': 5, 'max_aVWAPs': None },
              'OB': True,
              'OB_avg': False,
              'OB_params': { 'periods': 5, 'max_aVWAPs': 5 },
              'gaps': False,
              'gaps_avg': False,
              'gaps_params': { 'max_aVWAPs': 10 },
              'avg_lookback': 5,
              'keep_OB_column': True,
             },
    'StDev': {
              'centreline': 'peaks_valleys_avg', 
              'peaks_valleys_params': { 'periods': 5, 'max_aVWAPs': None }, 
              # 'gaps_params': { 'max_aVWAPs': 10 }, 
              'std_lookback': 10,
              'avg_lookback': 5,
              },
    'SMA': {'periods': [21]},
    'TTM_squeeze': {'bb_length': 20, 
                    'bb_std_dev': 2.0, 
                    'kc_length': 20, 
                    'kc_mult': 1.5, 
                    'use_true_range': True},
    # 'divergence_ATR':    {'period':  80, 'lookback': 30},
    'divergence_OBV':    {'period': 100, 'lookback': 40},
    'divergence_Volume': {'period': 100, 'lookback': 40},
    'divergence_Fisher': {'period': 100, 'lookback': 40},
    'divergence_Vortex': {'period': 100, 'lookback': 40},
}

params_daily = {
    'candle_colors': {'indicator_color': 'StDev', 
                      'custom_params': {'StDev': {'std_lookback': 10, 
                                                  'avg_lookback': 10,
                                                  'centreline': 'peaks_valleys_avg',
                                                  'peaks_valleys_params': {
                                                      'periods': 10,
                                                      'max_aVWAPs': None
                                                  }}}},
    'aVWAP': { 
              'peaks_valleys': False,
              'peaks_valleys_avg': True,
              'peaks_valleys_params': { 'periods': 21, 'max_aVWAPs': None },
              'OB': True,
              'OB_avg': False,
              'OB_params': { 'periods': 21, 'max_aVWAPs': 5 },
              'gaps': False,
              'gaps_avg': False,
              'gaps_params': { 'max_aVWAPs': 10 },
              'avg_lookback': 5,
              'keep_OB_column': True,
             },
    'StDev': {
              'centreline': 'peaks_valleys_avg', 
              'peaks_valleys_params': { 'periods': 20, 'max_aVWAPs': None }, 
              # 'gaps_params': { 'max_aVWAPs': 10 }, 
              'std_lookback': 75,
              'avg_lookback': 21,
              },
    'SMA': {'periods': [21]},
    'TTM_squeeze': {'bb_length': 21, 
                    'bb_std_dev': 2.0, 
                    'kc_length': 21, 
                    'kc_mult': 1.5, 
                    'use_true_range': True},
    # 'divergence_ATR':    {'period':  80, 'lookback': 30},
    'divergence_OBV':    {'period': 100, 'lookback': 40},
    'divergence_Volume': {'period': 100, 'lookback': 40},
    'divergence_Fisher': {'period': 100, 'lookback': 40},
    'divergence_Vortex': {'period': 100, 'lookback': 40},
}

params_1hour = {
    'candle_colors': {'indicator_color': 'StDev', 
                      'custom_params': {'StDev': {'std_lookback': 16, 
                                                  'avg_lookback': 16,
                                                  'centreline': 'peaks_valleys_avg',
                                                  'peaks_valleys_params': {
                                                      'periods': 16,
                                                      'max_aVWAPs': None
                                                  }}}},
    'aVWAP': { 
              'peaks_valleys': False,
              'peaks_valleys_avg': True,
              'peaks_valleys_params': { 'periods': 21, 'max_aVWAPs': None },
              'OB': True,
              'OB_avg': False,
              'OB_params': { 'periods': 21, 'max_aVWAPs': 5 },
              'gaps': False,
              'gaps_avg': False,
              'gaps_params': { 'max_aVWAPs': 10 },
              'avg_lookback': 5,
              'keep_OB_column': True,
             },
    'StDev': {
              'centreline': 'peaks_valleys_avg', 
              'peaks_valleys_params': { 'periods': 21, 'max_aVWAPs': None }, 
              # 'gaps_params': { 'max_aVWAPs': 10 }, 
              'std_lookback': 75,
              'avg_lookback': 21,
              },
    'SMA': {'periods': [21]},
    'TTM_squeeze': {'bb_length': 20, 
                    'bb_std_dev': 2.0, 
                    'kc_length': 20, 
                    'kc_mult': 1.5, 
                    'use_true_range': True},
    # 'divergence_ATR':    {'period':  80, 'lookback': 30},
    'divergence_OBV':    {'period': 100, 'lookback': 40},
    'divergence_Volume': {'period': 100, 'lookback': 40},
    'divergence_Fisher': {'period': 100, 'lookback': 40},
    'divergence_Vortex': {'period': 100, 'lookback': 40},
}

params_5min = {
    'candle_colors': {'indicator_color': 'StDev', 
                      'custom_params': {'StDev': {'std_lookback': 20, 
                                                  'avg_lookback': 20,
                                                  'centreline': 'peaks_valleys_avg',
                                                  'peaks_valleys_params': {
                                                      'periods': 20,
                                                      'max_aVWAPs': None
                                                  }}}},
    'aVWAP': { 
              'peaks_valleys': False,
              'peaks_valleys_avg': True,
              'peaks_valleys_params': { 'periods': 21, 'max_aVWAPs': None },
              'OB': True,
              'OB_avg': False,
              'OB_params': { 'periods': 21, 'max_aVWAPs': 5 },
              'gaps': False,
              'gaps_avg': False,
              'gaps_params': { 'max_aVWAPs': 10 },
              'avg_lookback': 5,
              'keep_OB_column': True,
             },
    'StDev': {
              'centreline': 'peaks_valleys_avg', 
              'peaks_valleys_params': { 'periods': 20, 'max_aVWAPs': None }, 
              # 'gaps_params': { 'max_aVWAPs': 10 }, 
              'std_lookback': 75,
              'avg_lookback': 21,
              },
    'SMA': {'periods': [21]},
    'TTM_squeeze': {'bb_length': 20, 
                    'bb_std_dev': 2.0, 
                    'kc_length': 20, 
                    'kc_mult': 1.5, 
                    'use_true_range': True},
    # 'divergence_ATR':    {'period':  80, 'lookback': 30},
    'divergence_OBV':    {'period': 100, 'lookback': 40},
    'divergence_Volume': {'period': 100, 'lookback': 40},
    'divergence_Fisher': {'period': 100, 'lookback': 40},
    'divergence_Vortex': {'period': 100, 'lookback': 40},
}


